In [85]:
import numpy as np
print(np.__version__)

2.3.1


In [86]:
o=np.arange(10)
print(o)
o1=np.arange(1,16)
print(o1)
o2=np.arange(1,101,3)
print(o2)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[  1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49  52
  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100]


In [87]:
x=np.linspace(0,25,5)
print(x)
x1=np.linspace(0,100,20)
print(x1)

[ 0.    6.25 12.5  18.75 25.  ]
[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [88]:
o2=np.zeros(5)
print(o2)
o3=np.zeros((5,5,5))
print(o3)

[0. 0. 0. 0. 0.]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [89]:
o3=np.ones((5,5,5))
print(o3)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [90]:
n1=np.full((3,4,3),18)
print(n1)

i=np.eye(7)
print(i)
p=np.diag([4,7,9,2,3])
print(p)

[[[18 18 18]
  [18 18 18]
  [18 18 18]
  [18 18 18]]

 [[18 18 18]
  [18 18 18]
  [18 18 18]
  [18 18 18]]

 [[18 18 18]
  [18 18 18]
  [18 18 18]
  [18 18 18]]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[4 0 0 0 0]
 [0 7 0 0 0]
 [0 0 9 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]]


In [91]:
ra=np.random.random((4,5))
print(ra)
ra1=np.random.randint(0,25,(5,5))
print(ra1)

[[0.9535508  0.54852137 0.06054644 0.64506593 0.77509988]
 [0.89858014 0.72239469 0.07015449 0.44548063 0.8153917 ]
 [0.95550721 0.83024276 0.74361247 0.01972982 0.27915076]
 [0.96818062 0.10425228 0.4387219  0.17176691 0.11897911]]
[[20 23  2 16  1]
 [16 16 20  7 23]
 [ 8 21 24 14  4]
 [15 12  1  2 17]
 [21  9 14  2  9]]


In [92]:
'''
#Single dimension
import numpy as np
#total for five students
total=[]
for i in range(0,5):
    a=int(input(f"Student{i+1}, Total="))
    total.append(a)
output=np.array(total)
print(total)
print(output)

'''
#Two dimension
'''
#average of 5 students marks in 5 subjects
import numpy as np
li=[]
avg=[]
for i in range(0,5): #5 students
    li1=[]
    sum=0
    for j in range(0,5): #5 subject marks
        a=int(input(f"Student{i+1}, Mark in sub{j+1}"))
        li1.append(a)
        sum+=a
    li.append(li1)
    avg.append(sum/5)
print("List representation:\n",li)
arr=np.array(li)
print("Array representation: \n",arr)
print(avg)

#Three dimension
import numpy as np
no_students= int(input("Enter number of students: "))
no_semesters= int(input("Enter number of semesters: "))
no_subjects= int(input("Enter number of subjects: "))
p_list=[]
for i in range(0,no_students):
    sem_list=[]
    for j in range(0, no_semesters):
        marks_list=[]
        for k in range(0, no_subjects):
            m=int(input(f"Student: {i+1} Semester: {j+1}, Enter mark in subject {k+1}: "))
            marks_list.append(m)
        sem_list.append(marks_list)
    p_list.append(sem_list)
print(p_list)
print(np.array(p_list))
'''


'\n#average of 5 students marks in 5 subjects\nimport numpy as np\nli=[]\navg=[]\nfor i in range(0,5): #5 students\n    li1=[]\n    sum=0\n    for j in range(0,5): #5 subject marks\n        a=int(input(f"Student{i+1}, Mark in sub{j+1}"))\n        li1.append(a)\n        sum+=a\n    li.append(li1)\n    avg.append(sum/5)\nprint("List representation:\n",li)\narr=np.array(li)\nprint("Array representation: \n",arr)\nprint(avg)\n\n#Three dimension\nimport numpy as np\nno_students= int(input("Enter number of students: "))\nno_semesters= int(input("Enter number of semesters: "))\nno_subjects= int(input("Enter number of subjects: "))\np_list=[]\nfor i in range(0,no_students):\n    sem_list=[]\n    for j in range(0, no_semesters):\n        marks_list=[]\n        for k in range(0, no_subjects):\n            m=int(input(f"Student: {i+1} Semester: {j+1}, Enter mark in subject {k+1}: "))\n            marks_list.append(m)\n        sem_list.append(marks_list)\n    p_list.append(sem_list)\nprint(p_list)

In [95]:
##Numpy (11-05-26)
st="Python is a high-level, interpreted programming language used for building websites, software, automation, artificial intelligence, data science, games, and more. It is known for its simple and easy-to-read syntax."
print(st)
ar=st.split(" ")
print(ar)
ar1=np.array(ar)
print(ar1)
uniquewords,count=np.unique(ar1,return_counts=True)
print(uniquewords)
print(count)
o=dict(zip(uniquewords,count))
print(o)

Python is a high-level, interpreted programming language used for building websites, software, automation, artificial intelligence, data science, games, and more. It is known for its simple and easy-to-read syntax.
['Python', 'is', 'a', 'high-level,', 'interpreted', 'programming', 'language', 'used', 'for', 'building', 'websites,', 'software,', 'automation,', 'artificial', 'intelligence,', 'data', 'science,', 'games,', 'and', 'more.', 'It', 'is', 'known', 'for', 'its', 'simple', 'and', 'easy-to-read', 'syntax.']
['Python' 'is' 'a' 'high-level,' 'interpreted' 'programming' 'language'
 'used' 'for' 'building' 'websites,' 'software,' 'automation,'
 'artificial' 'intelligence,' 'data' 'science,' 'games,' 'and' 'more.'
 'It' 'is' 'known' 'for' 'its' 'simple' 'and' 'easy-to-read' 'syntax.']
['It' 'Python' 'a' 'and' 'artificial' 'automation,' 'building' 'data'
 'easy-to-read' 'for' 'games,' 'high-level,' 'intelligence,' 'interpreted'
 'is' 'its' 'known' 'language' 'more.' 'programming' 'scien